# Generated by Django 3.0.8 on 2022-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerTree', '0002_workers_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='salary',
            field=models.IntegerField(verbose_name='name'),
        ),
    ]
