# Generated by Django 3.0.8 on 2022-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerTree', '0005_alter_workers_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
